---
version: '3'
services:
  riff-server:
    build: riff-server
    ports:
      - '3000:3000'
    volumes:
      - ${RIFF_SERVER_PATH-../riff-server}:/app
    depends_on:
      - mongo-server
  riff-rtc:
    build: riff-rtc
    ports:
      - '3001:3001'
    volumes:
      - ${RIFF_RTC_PATH-../riff-rtc}:/app
    depends_on:
      - riff-server
  web-server:
    build: web-server
    ports:
      - '80:80'
    volumes:
        - ${RIFF_RTC_PATH-../riff-rtc}/build:/usr/share/nginx/html/rtc:ro
    depends_on:
      - riff-rtc
      - riff-server
  mongo-server:
    image: mongo:latest
    volumes:
      - ${RIFF_DB_PATH-./mongodata}:/data/db
