---
# override/additions to docker-compose.yml for deploying to a swarm
# $ docker stack deploy -c docker-compose.yml -c docker-swarm.yml STACK_NAME
version: '3.6'
services:
  # The visualizer service is only needed when running in a swarm stack
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  riff-server:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  riff-rtc:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    configs:
      - source: riff-rtc.local-production.yml.7.debug
        target: /app/config/local-production.yml

  mongo-server:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  redis-server:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  signalmaster:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    configs:
      - source: signalmaster.local-production.yml.1
        target: /app/config/local-production.yml

  web-server:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

configs:
  riff-rtc.local-production.yml.7.debug:
    external: true
  signalmaster.local-production.yml.1:
    external: true
